name: Deploy Webhook API to Azure

on:
  push:
    branches: [ main ]

env:
  APP_NAME: webhook-api
  RESOURCE_GROUP: bananagold-rg
  CONTAINER_ENV: bananagold-env
  REGION: australiaeast
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        app-name: ${{ env.APP_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}
        container-app-env: ${{ env.CONTAINER_ENV }}
        image: ${{ env.IMAGE_NAME }}
        target-port: 80
        environment-variables: |
          WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
